swagger: "2.0"
info:
  title: Feed Generator
  description: Generates feed for different types of media
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /feed/manga:
    post:
      tags:
      - feedgen
      summary: manga feedgen
      operationId: feedgen#manga
      parameters:
      - name: feedType
        in: query
        description: RSS, Atom, or JSON Feed
        required: false
        type: string
        default: json
        enum:
        - rss
        - atom
        - json
      - name: MangaRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/FeedgenMangaRequestBody'
          required:
          - titles
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
      schemes:
      - http
  /feed/manga/{hash}:
    get:
      tags:
      - feedgen
      summary: viewManga feedgen
      operationId: feedgen#viewManga
      parameters:
      - name: hash
        in: path
        description: Identifier of previously created manga feed
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
      schemes:
      - http
definitions:
  FeedgenMangaRequestBody:
    title: FeedgenMangaRequestBody
    type: object
    properties:
      titles:
        type: array
        items:
          type: string
          example: Soluta repudiandae libero architecto.
        description: List of manga titles to subscribe to
        example:
        - Labore molestiae.
        - Neque alias.
        minItems: 1
        maxItems: 65535
    example:
      titles:
      - Blanditiis nesciunt molestias nostrum vel qui.
      - Doloremque soluta amet pariatur autem.
      - Quas impedit ratione esse.
    required:
    - titles
