swagger: "2.0"
info:
  title: RSS Fen
  description: Generates RSS feed for media
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /feed/manga:
    post:
      tags:
      - feedgen
      summary: manga feedgen
      operationId: feedgen#manga
      parameters:
      - name: MangaRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/FeedgenMangaRequestBody'
          required:
          - titles
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
      schemes:
      - http
definitions:
  FeedgenMangaRequestBody:
    title: FeedgenMangaRequestBody
    type: object
    properties:
      titles:
        type: array
        items:
          type: string
          example: Accusantium fuga ut.
        description: List of manga titles to subscribe to
        example:
        - Nihil repellendus animi dolorum omnis sint ab.
        - Aut incidunt eveniet sed.
        - Omnis odit.
        minItems: 1
    example:
      titles:
      - Vel nisi.
      - Optio id et laudantium.
      - Porro eveniet qui.
    required:
    - titles
