swagger: "2.0"
info:
  title: Feed Generator
  description: Generates feed for different types of media
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /feed/manga:
    post:
      tags:
      - feedgen
      summary: manga feedgen
      operationId: feedgen#manga
      parameters:
      - name: feedType
        in: query
        description: RSS, Atom, or JSON Feed
        required: false
        type: string
        default: json
        enum:
        - rss
        - atom
        - json
      - name: MangaRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/FeedgenMangaRequestBody'
          required:
          - titles
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
      schemes:
      - http
definitions:
  FeedgenMangaRequestBody:
    title: FeedgenMangaRequestBody
    type: object
    properties:
      titles:
        type: array
        items:
          type: string
          example: Officia qui fuga porro quia ut id.
        description: List of manga titles to subscribe to
        example:
        - Dolor ratione.
        - Adipisci dolores ab fuga magni.
        - Repudiandae libero architecto.
        minItems: 1
        maxItems: 65535
    example:
      titles:
      - Labore molestiae.
      - Neque alias.
    required:
    - titles
