swagger: "2.0"
info:
  title: Feed Generator
  description: Generates update feeds for different types of media 
  version: ""
schemes:
- "http"
consumes:
- application/json
- application/xml
produces:
- application/json
- application/xml
paths:
  /api/feed/manga:
    post:
      summary: Create feed from manga titles
      description: Creates a URL containing the current feed for the requested manga titles
      operationId: feedgen#Manga
      parameters:
      - name: MangaRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/FeedgenMangaRequestBody'
          required:
          - titles
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "404":
          description: Not Found response.
        "500":
          description: Internal Server Error response.
        "502":
          description: Bad Gateway response.
  /api/feed/manga/{hash}/titles/:
    get:
      summary: Get manga titles inside feed
      operationId: feedgen#viewMangaTitles
      produces:
        - application/json
      parameters:
      - name: hash
        in: path
        description: Identifier of previously created manga feed
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: object
            properties:
              titles:
                type: array
                items:
                  type: string
        "404":
          description: Not Found response.
        "500":
          description: Internal Server Error response.
        "502":
          description: Bad Gateway response.
  /api/feed/manga/{hash}:
    get:
      summary: Get feed of manga updates
      description: Returns an RSS/Atom/JSON Feed of the manga titles.
      operationId: feedgen#viewManga
      produces:
      - application/xml
      - application/json
      parameters:
      - name: hash
        in: path
        description: Identifier of previously created manga feed
        required: true
        type: string
      - name: feedType
        in: query
        description: RSS, Atom, or JSON Feed
        required: false
        type: string
        default: atom
        enum:
        - rss
        - atom
        - json
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "404":
          description: Not Found response.
        "500":
          description: Internal Server Error response.
        "502":
          description: Bad Gateway response.
definitions:
  FeedgenMangaRequestBody:
    title: FeedgenMangaRequestBody
    type: object
    properties:
      titles:
        type: array
        items:
          type: string
          example: Oyasumi Punpun
        description: List of manga titles to subscribe to
        example:
        - Oyasumi Punpun
        - Berserk
        minItems: 1
        maxItems: 2048
    example:
      titles:
      - Oyasumi Punpun
    required:
    - titles
