#cloud-config
# update and install packages
package_update: false
package_upgrade: true
packages: [ git, make, apt-transport-https, ca-certificates, curl, software-properties-common, gnupg2 ]

runcmd:
 - [ sh, -c, 'curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -' ]
 - [ sh, -c, 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"' ]
 - [ apt-get, update ]
 - [ apt-get, install, -y, docker-ce ]
 - [ sh, -c, 'curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose' ]
 - [ chmod, +x, /usr/local/bin/docker-compose ]
 - [ git, clone, https://github.com/Danlock/feedgen.git, ~/feedgen]

 # Add default auto created user to docker group
system_info:
    default_user:
        groups: [docker]