version: '3.7'
volumes:
  dbvol:

services:
  db:
    image: cockroachdb/cockroach:v2.1.6
    env_file: .env
    volumes:
      - dbvol:/cockroach/cockroach-data
      - ./init-user-db.sh:/etc/cockroach/conf/init-user-db.sh
      - ./schema.sql:/etc/cockroach/conf/schema.sql
    ports:
      - 26257:26257
      - 28080:8080
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    command: shell -c '/etc/cockroach/conf/init-user-db.sh & /cockroach/cockroach start --insecure --logtostderr=INFO;'
  poll:
    image: feedgen:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 18080:18080
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "100"
    command: poll $FG_POLL_DURATION
  api:
    image: feedgen:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 18081:18080
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "100"
    volumes:
      - ../ui/web/:${FG_UI}
    command: api http://feedgen.xyz